Repository Spirals-Team/repairnator, pull requests merged in 2018-10, with the labels that each got.

#738 Fix scanner for Bears
  repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java
  repairnator/repairnator-scanner/src/test/java/fr/inria/spirals/repairnator/scanner/ProjectScannerTest.java
Labels: Ready

#742 Update doc and fix dockerfile for pipeline-dev
  doc/contributing/repairnator-docker-image.md
  repairnator/docker-images/pipeline-dockerimage-dev/Dockerfile
Labels: Ready

#748 Updated mongoose to 5.3 (issue #747)
  website/repairnator-mongo-rest-api/index.js
  website/repairnator-mongo-rest-api/package.json
  website/repairnator-mongo-rest-api/yarn.lock
Labels: Ready

#751 Website enhancements (vue, api helper, notifications, buildinfo modal)
  website/repairnator-site/.gitignore
  website/repairnator-site/README.md
  website/repairnator-site/app/index.html
  website/repairnator-site/app/scripts/all-builds-bar.js
  website/repairnator-site/app/scripts/api.js
  website/repairnator-site/app/scripts/notification.js
  website/repairnator-site/app/scripts/realtime_values.js
  website/repairnator-site/app/scripts/scanner-seip.js
  website/repairnator-site/app/scripts/scanner_timechart.js
  website/repairnator-site/app/scripts/statuses_pie.js
  website/repairnator-site/app/styles/custom.sass
  website/repairnator-site/app/styles/main.scss
  website/repairnator-site/bower.json
  website/repairnator-site/config.exemple/default.json
  website/repairnator-site/config.exemple/development.json
  website/repairnator-site/config.exemple/production.json
  website/repairnator-site/gulpfile.js
  website/repairnator-site/package-lock.json
  website/repairnator-site/package.json
  website/repairnator-site/yarn.lock
Labels: enhancement

#736 Add support for Smtp authentication
  repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/Launcher.java
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/notifier/engines/EmailNotifierEngine.java
  repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
  repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
  repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
  repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
  repairnator/scripts/config/repairnator.cfg
  repairnator/scripts/launch_checkbranches.sh
  repairnator/scripts/launch_dockerpool.sh
  repairnator/scripts/launch_rtscanner.sh
  repairnator/scripts/launch_scanner.sh
  repairnator/scripts/repair_buggy_build.sh
  repairnator/scripts/reproduce_BEARS_failing-passing_builds.sh
Labels: WIP

#765 vueified realtime table + add pages
  website/repairnator-site/app/index.html
  website/repairnator-site/app/scripts/realtime_values.js
Labels: Ready

#757 added options to the config-file
  repairnator/docker-images/bears-dockerimage/Dockerfile
  repairnator/docker-images/bears-dockerimage/pipeline_launcher4Bears.sh
  repairnator/docker-images/pipeline-dockerimage-dev/Dockerfile
  repairnator/docker-images/pipeline-dockerimage-dev/pipeline_launcher.sh
  repairnator/docker-images/pipeline-dockerimage/Dockerfile
  repairnator/docker-images/pipeline-dockerimage/pipeline_launcher.sh
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/notifier/engines/EmailNotifierEngine.java
Labels: Ready

#766 [website] Put the components into a proper component folder
  website/repairnator-site/app/components/grid.js
  website/repairnator-site/app/components/pagination.js
  website/repairnator-site/app/index.html
  website/repairnator-site/app/scripts/realtime_values.js
  website/repairnator-site/gulpfile.js
Labels: Ready

#775 Remove unnecessary field (serializeJson) from RepairnatorConfig
  repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/Launcher.java
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfigReader.java
  repairnator/repairnator-core/src/test/java/fr/inria/spirals/repairnator/config/TestRepairnatorConfig.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
  repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
Labels: Ready

#746 Automatic Repair of Checkstyle Errors
  repairnator/docker-images/pipeline-dockerimage-dev/pipeline_launcher.sh
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/states/LauncherMode.java
  repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/states/PipelineState.java
  repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
  repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector4Checkstyle.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/maven/MavenHelper.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/Checkstyle.java
  repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorSerializer.java
  repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
  repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTScanner.java
  repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java
  repairnator/scripts/launch_cs_dockerpool.sh
  repairnator/scripts/launch_cs_rtscanner.sh
Labels: WIP
